#!/bin/sh
set -e

if [ -f /etc/tedge/operations/c8y/c8y_Command ]; then
    echo "Removing legacy file" >&2
    # regular file exists (is not a symlink)
    rm /etc/tedge/operations/c8y/c8y_Command
fi
